baseURL = "/"
languageCode = "en-us"
title = "Execute Big"

disableHugoGeneratorInject = true

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.announcement]
    show = true

  [params.logo]
    mobile = "images/logo-mobile.svg"
    desktop = "images/logo.svg"
    desktop_height = "36px"
    alt = "Execute Big Pig"

  [params.homepage_meta_tags]
    meta_description = "A minimal, 100% transparent student-run organization founded to enable all students to experience and explore computer science education."
    meta_og_title = "Execute Big"
    meta_og_type = "website"
    meta_og_url = "https://executebig.org"
    meta_og_image = "https://executebig.org/banner.png"
    meta_og_description = "A minimal, 100% transparent student-run organization founded to enable all students to experience and explore computer science education."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@executebig"
    meta_twitter_creator = "@executebig"

  [params.footer]
    copyright_text = '&copy;2019-2020 Execute Big.'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Programs"
    url = "/programs/"
      weight = 1

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 2

  # Footer Menu
  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
